# Generated by Django 5.2.8 on 2026-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscription',
            name='language',
            field=models.CharField(default='ar', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='botsubscription',
            name='last_main_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Last Main Message ID'),
        ),
    ]
