# Generated by Django 5.2.8 on 2026-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botsubscription_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbot',
            name='bot_type',
            field=models.CharField(choices=[('CON', 'Contact Bot'), ('LST', 'List Bot')], default='CON', max_length=3, verbose_name='Bot Type'),
        ),
    ]
