# Generated by Django 5.2.8 on 2026-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_subbot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbot',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
