# Generated by Django 5.2.8 on 2026-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_subbot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbot',
            name='welcome_msg',
            field=models.TextField(blank=True, default='Default Welcome Message', help_text='The message shown to users when they send /start', null=True, verbose_name='Welcome Message'),
        ),
    ]
