# Generated by Django 5.2.8 on 2026-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_subbot_welcome_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbot',
            name='welcome_msg',
            field=models.TextField(blank=True, help_text='The message shown to users when they send /start', null=True, verbose_name='Welcome Message'),
        ),
    ]
