# Generated by Django 5.2.8 on 2026-03-23 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("bots", "0007_subbot_welcome_parse_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="invite_link",
            field=models.URLField(blank=True, null=True, verbose_name="Invite Link"),
        ),
        migrations.AddField(
            model_name="subbot",
            name="owner_buttons",
            field=models.TextField(
                blank=True,
                help_text="Format: Button Name | URL (one per line)",
                null=True,
                verbose_name="Owner Custom Buttons",
            ),
        ),
        migrations.AddField(
            model_name="subbot",
            name="template_msg",
            field=models.TextField(default=1, verbose_name="Template msg"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subbot",
            name="teplate_parse_mode",
            field=models.CharField(
                choices=[
                    ("HTML", "HTML"),
                    ("MDV2", "Markdown V2"),
                    ("PLAIN", "Plain Text"),
                ],
                default="HTML",
                max_length=5,
                verbose_name="List Message Format",
            ),
        ),
        migrations.CreateModel(
            name="SubBotChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "custom_invite_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Custom Link for this Bot"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_bots",
                        to="bots.channel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to="accounts.telegramuser",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "sub_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_channels",
                        to="bots.subbot",
                    ),
                ),
            ],
            options={
                "unique_together": {("sub_bot", "channel")},
            },
        ),
    ]
