# Generated by Django 5.2.8 on 2026-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_channel_invite_link_subbot_owner_buttons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Username"
            ),
        ),
    ]
