# Generated by Django 5.2.8 on 2026-03-24 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("bots", "0009_channel_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "header_text",
                    models.TextField(
                        blank=True,
                        help_text="The text that appears above the channel list",
                        null=True,
                        verbose_name="Header Text",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="The text that appears at the bottom of the channel list",
                        null=True,
                        verbose_name="Footer Text",
                    ),
                ),
                (
                    "post_interval",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="How many hours are there between each automatic posting?",
                        verbose_name="Post Every (Hours)",
                    ),
                ),
                (
                    "delete_after",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="After how many hours will the list be deleted from the channels? (0 means do not delete)",
                        verbose_name="Delete After (Hours)",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Auto Posting Enabled"
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Run Time"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to="accounts.telegramuser",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "sub_bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_config",
                        to="bots.subbot",
                        verbose_name="Sub Bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "List Template",
                "verbose_name_plural": "List Templates",
            },
        ),
        migrations.CreateModel(
            name="PublishedList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("channel_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField()),
                ("delete_at", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to="accounts.telegramuser",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "sub_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bots.subbot"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
