# Generated by Django 5.2 on 2026-06-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_adminchannel_is_frozen_botsubscription_is_frozen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbot',
            name='support_link',
            field=models.URLField(blank=True, null=True, verbose_name='Support/Contact Link'),
        ),
    ]
