# Generated by Django 5.2.8 on 2026-03-19 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Is Partner')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Available Balance')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pending Balance')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Earned')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('preferred_method', models.CharField(choices=[('CRY', 'Crypto (USDT)'), ('PAL', 'PayPal'), ('BNK', 'Bank Transfer'), ('CSH', 'Local Wallet (Cash)')], default='CSH', max_length=3, verbose_name='Preferred Payout Method')),
                ('payout_details', models.TextField(blank=True, null=True, verbose_name='Payout Details')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('tx_type', models.CharField(choices=[('EAR', 'Earning'), ('WTH', 'Withdrawal'), ('REF', 'Referral Commission')], max_length=3, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Completed'), ('FAI', 'Failed/Rejected')], default='PEN', max_length=3, verbose_name='Status')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason/Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
