# Generated by Django 5.2 on 2026-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
    ]
