# Generated by Django 5.2.8 on 2026-03-19 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('channel_id', models.BigIntegerField(unique=True, verbose_name='Channel ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('force_msg', models.TextField(blank=True, null=True, verbose_name='Force Subscribe Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('channel_id', models.BigIntegerField(unique=True, verbose_name='Channel ID')),
                ('title', models.CharField(max_length=255, verbose_name='Channel Title')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Member Count')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('LFT', 'Bot Left'), ('BAN', 'Banned'), ('REF', 'Needs Refresh')], default='ACT', max_length=3, verbose_name='Status')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Last Sync')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_channels', to='accounts.telegramuser', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='SubBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Bot Token')),
                ('name', models.CharField(max_length=255, verbose_name='Bot Name')),
                ('bot_type', models.CharField(choices=[('SUP', 'Support Bot'), ('CON', 'Contact Bot'), ('LST', 'List Bot')], default='SUP', max_length=3, verbose_name='Bot Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('force_msg', models.TextField(blank=True, null=True, verbose_name='Force Subscribe Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
                ('force_channels', models.ManyToManyField(blank=True, related_name='forced_in_bots', to='bots.channel', verbose_name='Force Subscribe Channels')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bots', to='accounts.telegramuser', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Sub Bot',
                'verbose_name_plural': 'Sub Bots',
            },
        ),
        migrations.CreateModel(
            name='BotSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.telegramuser', verbose_name='Created By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.telegramuser', verbose_name='User')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='bots.subbot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Bot Subscription',
                'verbose_name_plural': 'Bot Subscriptions',
                'unique_together': {('bot', 'user')},
            },
        ),
    ]
