# Generated by Django 5.2.8 on 2026-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_alter_subbot_welcome_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="subbot",
            name="welcome_parse_mode",
            field=models.CharField(
                choices=[
                    ("HTML", "HTML"),
                    ("MDV2", "Markdown V2"),
                    ("PLAIN", "Plain Text"),
                ],
                default="HTML",
                max_length=5,
                verbose_name="Welcome Message Format",
            ),
        ),
        migrations.AlterField(
            model_name="adminchannel",
            name="channel_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Channel ID"
            ),
        ),
    ]
