# Generated by Django 5.2 on 2026-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_mandatory_channels_list_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchannel',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Shown on mandatory-subscribe buttons', max_length=255, verbose_name='Display title'),
        ),
        migrations.AlterField(
            model_name='platformlistbutton',
            name='callback_hint',
            field=models.CharField(blank=True, default='', help_text='Shown as alert when user taps a callback-type button', max_length=180, verbose_name='Callback note'),
        ),
        migrations.AlterField(
            model_name='subbotlistbutton',
            name='callback_hint',
            field=models.CharField(blank=True, default='', help_text='Shown as alert when user taps a callback-type button', max_length=180, verbose_name='Callback note'),
        ),
    ]
