# Generated by Django 5.2 on 2026-06-05 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramuser_is_frozen_transaction_is_frozen_and_more'),
        ('bots', '0013_alter_adminchannel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchannel',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='botsubscription',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='platformlistbutton',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='publishedlist',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='subbot',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='subbotchannel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_bot_channels', to='accounts.telegramuser', verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='subbotchannel',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='subbotlistbutton',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='subbotmandatorychannel',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
        migrations.AddField(
            model_name='subbotsubscriptionquota',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is Frozen'),
        ),
    ]
